if(NOT DEFINED STAGE_DIR)
    message(FATAL_ERROR "STAGE_DIR is required")
endif()

if(APPLE)
    set(host "${STAGE_DIR}/app/agent_plugin_host.app")
    set(scanner "${STAGE_DIR}/scanner/agent_plugin_scanner")
elseif(WIN32)
    set(host "${STAGE_DIR}/app/agent_plugin_host.exe")
    set(scanner "${STAGE_DIR}/scanner/agent_plugin_scanner.exe")
else()
    set(host "${STAGE_DIR}/app/agent_plugin_host")
    set(scanner "${STAGE_DIR}/scanner/agent_plugin_scanner")
endif()

set(gain "${STAGE_DIR}/fixtures/aph_test_gain.vst3")
set(synth "${STAGE_DIR}/fixtures/aph_test_synth.vst3")
set(manifest "${STAGE_DIR}/ARTIFACTS.txt")

foreach(path IN ITEMS "${host}" "${scanner}" "${gain}" "${synth}" "${manifest}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing staged artifact: ${path}")
    endif()
endforeach()

if(APPLE)
    set(gain_au "${STAGE_DIR}/fixtures/aph_test_gain.component")
    set(synth_au "${STAGE_DIR}/fixtures/aph_test_synth.component")
    foreach(path IN ITEMS "${gain_au}" "${synth_au}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "Missing staged artifact: ${path}")
        endif()
    endforeach()

    foreach(bundle IN ITEMS "${host}" "${gain}" "${synth}" "${gain_au}" "${synth_au}")
        execute_process(COMMAND codesign --verify --deep --strict "${bundle}"
                        RESULT_VARIABLE result ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Invalid ad-hoc signature for ${bundle}: ${error}")
        endif()
    endforeach()
endif()
